### ISSUE TITLE
为啥要用gradle。。。。

### ISSUE THREAD

**Issue by qijunyu** [iisquare/etl-visual#3]
还有能不能提供一个本地部署的文档

**Comment by iisquare** [comment]
### 前端（/static/admin）
- 用户：admin
- 密码：admin888
### 服务（/docker）
- Redis：存储Session
- MySQL：数据脚本（/java/docs）
### 后端（/java）
- web.admin：后端接口
- web.member：用户中心
### 其他
- 功能模块可自行分析，按需运行
